module.exports = [
	{
		key: "people-and-portraits",
		title: "People & Portraits",
		description: "Portrait studies and candid moments.",
		url: "/galleries/people-and-portraits/",
		cover: "content/galleries/people-and-portraits/0002.jpg",
		previewImages: [
			"content/galleries/people-and-portraits/0002.jpg",
			"content/galleries/people-and-portraits/0004.jpg",
			"content/galleries/people-and-portraits/0008.jpg",
			"content/galleries/people-and-portraits/0009.jpg",
			"content/galleries/people-and-portraits/0012.jpg",
		],
	},
	{
		key: "landscapes-and-horizons",
		title: "Landscapes & Horizons",
		description: "Open horizons and wide vistas.",
		url: "/galleries/landscapes-and-horizons/",
		cover: "content/galleries/landscapes-and-horizons/0015.jpg",
		previewImages: [
			"content/galleries/landscapes-and-horizons/0015.jpg",
			"content/galleries/landscapes-and-horizons/0019.jpg",
			"content/galleries/landscapes-and-horizons/0021.jpg",
			"content/galleries/landscapes-and-horizons/0029.jpg",
			"content/galleries/landscapes-and-horizons/0032.jpg",
		],
	},
	{
		key: "skies-and-waterscapes",
		title: "Skies & Waterscapes",
		description: "Clouds, water, and atmospheric light.",
		url: "/galleries/skies-and-waterscapes/",
		cover: "content/galleries/skies-and-waterscapes/0005.jpg",
		previewImages: [
			"content/galleries/skies-and-waterscapes/0005.jpg",
			"content/galleries/skies-and-waterscapes/0011.jpg",
			"content/galleries/skies-and-waterscapes/0018.jpg",
		],
	},
	{
		key: "soft-light-and-atmosphere",
		title: "Soft Light & Atmosphere",
		description: "Diffused light and quiet moods.",
		url: "/galleries/soft-light-and-atmosphere/",
		cover: "content/galleries/soft-light-and-atmosphere/0024.jpg",
		previewImages: [
			"content/galleries/soft-light-and-atmosphere/0024.jpg",
			"content/galleries/soft-light-and-atmosphere/0047.jpg",
			"content/galleries/soft-light-and-atmosphere/0060.jpg",
		],
	},
	{
		key: "street-and-shadow",
		title: "Street & Shadow",
		description: "Urban environments and contrasting light.",
		url: "/galleries/street-and-shadow/",
		cover: "content/galleries/street-and-shadow/0006.jpg",
		previewImages: [
			"content/galleries/street-and-shadow/0006.jpg",
			"content/galleries/street-and-shadow/0007.jpg",
			"content/galleries/street-and-shadow/0020.jpg",
		],
	},
	{
		key: "nature-and-botanicals",
		title: "Nature & Botanicals",
		description: "Quiet studies of plants and natural forms.",
		url: "/galleries/nature-and-botanicals/",
		cover: "content/galleries/nature-and-botanicals/0001.jpg",
		previewImages: [
			"content/galleries/nature-and-botanicals/0001.jpg",
			"content/galleries/nature-and-botanicals/0013.jpg",
			"content/galleries/nature-and-botanicals/0016.jpg",
		],
	},
	{
		key: "color-and-light",
		title: "Color & Light",
		description: "Bold color and light studies.",
		url: "/galleries/color-and-light/",
		cover: "content/galleries/color-and-light/0003.jpg",
		previewImages: [
			"content/galleries/color-and-light/0003.jpg",
			"content/galleries/color-and-light/0010.jpg",
			"content/galleries/color-and-light/0052.jpg",
		],
	},
	{
		key: "architecture-and-structure",
		title: "Architecture & Structure",
		description: "Built environments and structural forms.",
		url: "/galleries/architecture-and-structure/",
		cover: "content/galleries/architecture-and-structure/0022.jpg",
		previewImages: [
			"content/galleries/architecture-and-structure/0022.jpg",
			"content/galleries/architecture-and-structure/0025.jpg",
			"content/galleries/architecture-and-structure/0027.jpg",
		],
	},
];
